### ISSUE TITLE
Call instead of callvirt instructions are emitted when using coalesce operator for weaved members

### ISSUE THREAD

**Issue by Dresel** [Fody/Virtuosity#294]
When accessing weaved members within a solution outside of the weaved project call instead of callvirt instructions might be emitted when using the coalesce operator. To make this clearer consider the following setup:

- `VirtuosityCoalesce`
- `VirtuosityCoalesce.Assembly` (processed by Virtuosity.Fody)

If `VirtuosityCoalesce` references classes from `VirtuosityCoalesce.Assembly`, for example this

```csharp
ClassWeavedByVirtuosity instance = new ClassWeavedByVirtuosity();
instance.WeavedMethod(); // Emits callvirt
instance.?WeavedMethod(); // Emits call
```

will encounter the issue described above.

#### Minimal Repro

`git clone https://github.com/SpatialFocus/VirtuosityCoalesce.git`

```csharp
// Code in VirtuosityCoalesce.csproj
private static void Main(string[] args)
{
    ProxyGenerator generator = new ProxyGenerator();
    MyClass myClass = generator.CreateClassProxy<MyClass>(new MyClassInteceptor());

    myClass.Method1();
    myClass.Method2();

    myClass?.Method1();
    myClass?.Method2();
}

public class MyClassInteceptor : IInterceptor
{
    public void Intercept(IInvocation invocation) => Console.WriteLine($"{invocation.Method.Name}: Virtual call");
}

// Code in VirtuosityCoalesce.Assembly.csproj
public class MyClass
{
    public virtual void Method1() => Console.WriteLine("Method1: Non virtual call");
    public void Method2() => Console.WriteLine("Method2: Non virtual call");
}
```

This outputs the following:

```
Method1: Virtual call
Method2: Virtual call
Method1: Virtual call
Method2: Non virtual call
```

#### Make an effort to fix the bug

I would go for a PR, but I'm not even sure there is something we can do about it? The weaver can only process the assembly being weaved, not the referencing projects, right?

**Comment by Dresel** [comment]
As a workaround you could set a direct dll reference

```csproj
<ItemGroup>
    <Reference Include="VirtuosityCoalesce.Assembly">
        <HintPath>..\VirtuosityCoalesce.Assembly\bin\$(configuration)\$(targetframework)\VirtuosityCoalesce.Assembly.dll</HintPath>
    </Reference>
</ItemGroup>
```

and add a manual project dependency. See `reference-dll-workaround` branch of repo.

**Comment by ltrzesniewski** [comment]
> I would go for a PR, but I'm not even sure there is something we can do about it? The weaver can only process the assembly being weaved, not the referencing projects, right?

You're right, but I think there's something we can do here, actually.

Here's another workaround for the issue: add `<ProduceReferenceAssembly>false</ProduceReferenceAssembly>` to a `<PropertyGroup>` in `VirtuosityCoalesce.Assembly.csproj`.

The SDK started to set this property to `true` by default in .NET Core >= v5. It makes the compiler generate a reference assembly, and referencing projects will use the reference assembly for their build instead of the output assembly.

The issue comes from the fact that Virtuosity updates member signatures, but it doesn't do so for the reference assembly. Actually, this behavior _may_ be a problem for all those Fody addins that modify member signatures or add new members or classes.

I can see a few solutions:

 1. Add weaving support for reference assemblies in Fody. That's quite a bit of work, _and_ requires some addins such as Virtuosity to be updated to provide specific logic for reference assemblies.
 2. Set `ProduceReferenceAssembly` to `false` in a `Virtuosity.Fody.props` file (and in other addins that need this as well). That should be a quick fix.
 3. Set `ProduceReferenceAssembly` to `false` in a `Fody.props` file (so globally for all projects that use Fody). That's more of a "precaution" solution than a clean fix.

I suppose we could implement solution 2 quickly to solve this for Virtuosity, and then discuss whether we should implement solutions 1 or 3.

@SimonCropp do you know if many addins would be impacted by this issue?

**Comment by tom-englert** [comment]
Hard to say which weavers could be affected, and in which scenarios, and if that will have side effects.
If I read this correctly it can have a side effect on any weaver that changes the public interface of an assembly - including new stuff that won't be available to referencing projects, right?

**Comment by ltrzesniewski** [comment]
Yes, basically on .NET 5 referencing projects will by default see the metadata as it was *before* the weaving process (for projects in the same solution).

This led to bad codegen for projects that reference a project that uses Virtuosity, but I suppose (and I hope) that it shouldn't cause too much issues for most other weavers.

At least, any weaver that doesn't modify assembly metadata should be fine, and I suppose that weavers that add to the existing metadata shouldn't cause big issues (like for instance PropertyChanged which can add an implementation of `INotifyPropertyChanged` to a class shouldn't cause too much trouble if a referencing project doesn't see the change).

**Comment by tom-englert** [comment]
So for `INotifyPropertyChanged` injected via `[AddINotify...]` attribute the referencing project could not call `xyz.PropertyChanged += xyz_PropertyChanged(...`. 

So it will always be good for some surprises...

**Comment by ltrzesniewski** [comment]
Well, that particular example didn't work previously either, since both projects are loaded into a Roslyn workspace, which is unaware of the weaving. So the IDE would mark `PropertyChanged` as an unknown member. That's why I don't think it will really be a problem for this example.
